### ISSUE TITLE
Use the Angular Router

### ISSUE THREAD

**Issue by VicAv99** [eccentricnode/prayer-requests#1]
https://github.com/eccentricnode/prayer-requests/blob/56e0725089903a9c7dfb0dec9b15ae9ab3aa7f5d/apps/prayer-submit/src/app/app.component.html#L18

## Explanation:
Basically, what happens in the event you want to add a `HomeComponent` or an `About` Page or anything else? Instead of manually using the selectors for your components you can use the `router-outlet` to have the Angular Router dynamically route you to whatever component you need. Then in your side nav, you can have a list of your pages and have the router navigate a user from page to page.

## Implementation:
- create a `routing.module.ts` next to `app.module.ts`
- You will need to import `RouterModule` and `Routes` from `@angular/router`
-  Right under your imports, you will need to create a variable defining all of your routes
```
const routes: Routes = [
  // If nothing is typed, you will be redirected to the PrayersComponent
  { path: '', redirectTo: '/prayers', pathMatch: 'full' },
  { path: 'prayers', component: PrayerComponent },
  // If a random route is describes you will be redirected to '' which will redirect to PrayersComponent
  { path: '**', redirectTo: '', pathMatch: 'full' }
];
```
- In your `@NgModule` decorator you will need to both import and export the `RouterModule`, however, when importing you will need to pass in the routes variable to the `RouterModule`'s `forRoot` method like so.
```
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
```
- Next, you will have to go to your `app.module.ts` and import your newly created `RoutingModule`
- Now on this line I commented on you will refactor from `<prayers-prayer-requests></prayers-prayer-requests> ` to `<router-outlet></router-outlet>`
- You should now see `localhost:4200/prayers` on your browser.
- Lastly, make sure to include your new routes in your side nav (`app.component.ts`):

TS:
```
export class AppComponent implements OnInit {
  links = [
    { path: '/prayers', title, 'Prayers' }
  ];
}
```
HTML:
```
<nav>
  <a mat-button *ngFor="let link of links" 
    [routerLink]="link.path" 
    routerLinkActive="active">
    <mat-icon>
      {{link.icon}}
    </mat-icon>
      {{link.title}}
  </a>
</nav>
```

## Resources: 
Here are some links on how you could refactor your code to do this:
1. https://medium.com/all-is-web/https-medium-com-all-is-web-angular-5-routing-fad9b3648f67
2. https://blog.angularindepth.com/the-three-pillars-of-angular-routing-angular-router-series-introduction-fb34e4e8758e

**Comment by eccentricnode** [comment]
done
