### ISSUE TITLE
Add a Deploy Script

### ISSUE THREAD

**Issue by VicAv99** [eccentricnode/prayer-requests#3]
https://github.com/eccentricnode/prayer-requests/blob/214d80341f582fa40a423841622681429b354993/package.json#L8

## Explanation:
For faster deployment, I would add a deploy script for your app right under this one. As you know, there are a few commands to run for proper Angular + Surge deployment. Why not just create a script here to run them all for you?

## Implementation:
- Right under this script add:
`"deploy:prayers": "ng build && cp ./build/apps/prayer-submit/index.html ./build/apps/prayer-submit/200.html && surge ./build/apps/prayer-submit https://whatevery.surge.sh/`

**Comment by eccentricnode** [comment]
Taken care of
